### ISSUE TITLE
The problem about feature extraction

### ISSUE THREAD

**Issue by pranerd** [ASoleimaniB/DMML#2]
Hello,
        I read your code, it maybe that you didn't provide the code of feature extraction. So could you upload your code about feature extraction?
Thanks

**Comment by ASoleimaniB** [comment]
Hello,
Good to see you interested in my code. Sure, I will upload it in this weekend. Also please note that the HOG feature is ready for UTSig dataset now and has been currently uploaded

**Comment by pranerd** [comment]
Thank you, AsoleimaniB. but why did you delete the mat file which you have generated?

**Comment by ASoleimaniB** [comment]
That .mat file was not correct because of limit in uploading size in
GitHub. Diwnload it using the link in the readme.

**Comment by pranerd** [comment]
Thank you.
